# Generated by Django 3.1.2 on 2021-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='StatusChanged',
            field=models.CharField(default='No change!', max_length=30),
        ),
    ]
