# Generated by Django 3.1.2 on 2021-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerrecord_statuschanged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='subservice',
            field=models.CharField(max_length=100),
        ),
    ]
