# Generated by Django 3.1.2 on 2021-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0027_auto_20201230_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.TextField()),
            ],
        ),
    ]
