# Generated by Django 3.1.2 on 2021-01-08 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0028_latestupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestupdates',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
