# Generated by Django 3.1.2 on 2021-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitr', '0031_auto_20210108_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ExclusiveDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
